// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/client/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/client/test').default>>>>
    }
    '/api/feeds': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feeds/index').default>>>>
    }
    '/api/settings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings').default>>>>
    }
    '/api/torrents/:hash': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/torrents/[hash]').default>>>>
    }
    '/api/torrents': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/torrents/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
  }
}
export {}